import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/provider";
import { ThemeProvider } from "@mui/material";
import CustomAppBar from "./components/CustomAppBar/CustomAppBar";
import { Pathname } from "./components/pathname/pathname";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { getTokenFromCookie } from "./res/utils/cookieUtils";
import { CookiesProvider } from 'next-client-cookies/server';
// import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Inter({ subsets: ["latin"] });
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
export const metadata = {
  title: "ERP-V2",
  description: "Generated by ADM",
};

export default function RootLayout({ children }) {
  //   const cookieStore = cookies();
  //   const token = cookieStore.get("token");
  // (  () => {
  //     if (token) {
  //       redirect("/");
  //     }else{

  //     }
  //   })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <AntdRegistry> */}
          {/* <ThemeProvider > */}
          <CookiesProvider>
            <Pathname>{children}</Pathname>
          </CookiesProvider>
          {/* </ThemeProvider> */}
          {/* </AntdRegistry> */}
        </Providers>
      </body>
    </html>
  );
}
